language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
notifications:
  slack: gdgistanbul:MkGDF2g8vysFpns70TXa74AK
deploy:
# Beta
#- provider: firebase
#  skip_cleanup: true
#  on:
#    branch: beta
#  project: Beta-devfest17
#  token:
#    secure: H9Lqa5firEdSpp8k144J7XNDAcAdrOFNvIwn3RPaxtzS6IFnu72rVr66DAbMTYeqe3+od8c9ieAkxV4PTLa/Y4uxK5lSMLQcukWJumLgSjsAAvGzI7Al+xE6wGAb9DNvDJ4vH6D9j3ItC4gl4o6Bb0kjNtL+876IyFfbnuP7tj+IirKCcbwr7NhiZ4gfvfA2eiXnt+yR1ljBkEX75a3GgUvQD22+Y3YnHu8b7ItKFDAWPSWJ04PphoVPl6KvjYXssEKK3OGoZ0vXgBHtVbDJDYjbrcpXJfTIM1bxcr57s7YaxT8mXUQBWl4fOSXQb4Vb29f4jdKMj4lxSE6hYBaHhSH4uSTOsIlNR38MKX4na6jsgDYs2vhzog11CK2J+oSoPyV6p4nzPLSae/iibKJdhyE8FfnTOt9MiYdK70e7J1WWfnN2RZrxNPNmw/eFqZXqw7n3X+e9a01Ba9kNoO/6hFzaLqPXkRoeFo6oLsn628drn5BJW9nacTTEoOpKtLPBGY1eet6Qb1L75yYTUYwTBiv1suXI+jU9Ez1NuFuPoMYMhgqP+6Ht6/U1hw9LSIq/z9gQyE4Du1bYxRCjDLe9hb8ooaLlAp0ByZkGfXzikiKO0Pk3OUG1q+YqBoKvU8zLD1R1BH4r5d7CNbUej8kF7CPWVxWIjG/yVL4MxoKfnHI=
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-istanbul-devfest-2017
  token:
    secure: Quq/Ys1GKDYFjqMCD107saKj005L0RaM7Ian9yLIW/er4KdMzwjYw7TVXmtMeJPIfEy/e2/4WJ63K1SaXieBoFndoUcpGWqPOoTrnkkj5K7tzeZKM32XqIarF+BNmOoqW5M7+kuN8L7N3RLp00ywFDOgKgiZJeoaDV6sIRRAIFVh+xHWabVWpFCwCUSeBZpufOsZhMXkicyRe0XhMmkUvS1P5CI3AyZZdIfWG+sguFsPOWRjMFKWrbnsilDFDjf7N0Wd8Z1H2Z0LBn/V00bNb95MSIuOhkdk3a1wP0P5Eollet+Y8g+NpdWyFq0/C+6+ECvFLBjtvbtMY1BVfdxkCo5XlogZx31OmkMWVX6PXOD5Va8aFoJnwvjovUT8oZbSCWEuyMxI91jDsLxXZt542MNfUfQ1Q2+SpUShdcRlwoV2c/XOYvme95HnI1LSqzLubooKWxz8wpa/aovkdZbum54t/z5nA54AXN1lYKsi+hcAFHOeucqd/kHOLG0bx05Ev86wcvNH8qGx+v7S644YH37No7PGnKU3g3Jq/m6quo1B/bMEIaatVnR40D301wAi8tsNWnqEdWFKnAlGrTIDd1qek9OHnApmgBQI8o0FOy6WbzLMwl9PnMl+t+wew/ggSY0IdWhjFWR/S1d6xML8cYHXHVpE0wxkat5ETbIYXlg=
