language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
notifications:
  slack: gdgistanbul:MkGDF2g8vysFpns70TXa74AK
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdg-istanbul-devfest-2017
  token:
    secure: QcWnum2shF9PEBunr5958M8jZBD+012xBU83qqRhTCkZNbJ3B66EGkNIP3XZzZO3qChggTI7vg9y92aDZjK3XoJHlw2Xad18+MDAy+kg2xss5I9f2qKRwU0V4QwFVS5KXPjwwRotkEXh2/YMIN80AIWaZTfkunNChh4MvWw18/73PheWvWPDmbPpjq1MIl9tz4K8377uYbK9qz0eRsJhuXG50kpHVYUE39UF9DyQr0eFIBqjsPBeuxmq8GZeY5sX/bM9tIvydS8ADxzBuK3WwUWo21YRAJFcm2ZOykUiL0VvoQ6XMPEwcgj04MDYqdl1DSBCWgqlrqqpN40AhsQEv3gLUY0whwUS+LGRE2Wxc20x+fmePXrtRkhIV1KQTw2MA9kaDNeNdj5QgJHOAXzo3/p0/eBF8zYxM4PYXFbVAD5wb7SrEiHnGaUSGPofuhzvhmOujAAjHxag4TfMmWYYnt6TPwUEovKJoDk8d9znuE6r7B/BHOleiJ3+FBwDMd7uBxGT0Naz9nDF1DlTbAu1IZ8ps9svG4GSazGHewr1H4Sw5a9pUIg2k2xgM4qmn7FwPak6PkL7Oux/A88f2BcYMMZIKKvNa3O11+82GSg+n107p76/JKnwwUz4pkvPq0MzWCzTNVhr2syVZR76NuN6UlcvlvHwYEdys7XKKUeibmE=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: gdg-istanbul-devfest-2017
  token:
    secure: Quq/Ys1GKDYFjqMCD107saKj005L0RaM7Ian9yLIW/er4KdMzwjYw7TVXmtMeJPIfEy/e2/4WJ63K1SaXieBoFndoUcpGWqPOoTrnkkj5K7tzeZKM32XqIarF+BNmOoqW5M7+kuN8L7N3RLp00ywFDOgKgiZJeoaDV6sIRRAIFVh+xHWabVWpFCwCUSeBZpufOsZhMXkicyRe0XhMmkUvS1P5CI3AyZZdIfWG+sguFsPOWRjMFKWrbnsilDFDjf7N0Wd8Z1H2Z0LBn/V00bNb95MSIuOhkdk3a1wP0P5Eollet+Y8g+NpdWyFq0/C+6+ECvFLBjtvbtMY1BVfdxkCo5XlogZx31OmkMWVX6PXOD5Va8aFoJnwvjovUT8oZbSCWEuyMxI91jDsLxXZt542MNfUfQ1Q2+SpUShdcRlwoV2c/XOYvme95HnI1LSqzLubooKWxz8wpa/aovkdZbum54t/z5nA54AXN1lYKsi+hcAFHOeucqd/kHOLG0bx05Ev86wcvNH8qGx+v7S644YH37No7PGnKU3g3Jq/m6quo1B/bMEIaatVnR40D301wAi8tsNWnqEdWFKnAlGrTIDd1qek9OHnApmgBQI8o0FOy6WbzLMwl9PnMl+t+wew/ggSY0IdWhjFWR/S1d6xML8cYHXHVpE0wxkat5ETbIYXlg=
